const cfg = window.APP_CONFIG || {};
const configured = cfg.SUPABASE_URL && cfg.SUPABASE_PUBLISHABLE_KEY && !cfg.SUPABASE_URL.includes('PASTE_') && !cfg.SUPABASE_PUBLISHABLE_KEY.includes('PASTE_');
const client = configured ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_PUBLISHABLE_KEY) : null;
const $ = id => document.getElementById(id);

const els = {
  loginCard:$('loginCard'), adminApp:$('adminApp'), adminEmail:$('adminEmail'), adminPassword:$('adminPassword'), loginBtn:$('loginBtn'), loginMessage:$('loginMessage'),
  adminUser:$('adminUser'), logoutBtn:$('logoutBtn'), statStudents:$('statStudents'), statSelections:$('statSelections'), statCourses:$('statCourses'), statEntries:$('statEntries'), statOverlaps:$('statOverlaps'),
  registrationStatusBadge:$('registrationStatusBadge'), toggleRegistrationBtn:$('toggleRegistrationBtn'), catalogStatusText:$('catalogStatusText'), closedMessageInput:$('closedMessageInput'), saveStatusBtn:$('saveStatusBtn'), statusMessage:$('statusMessage'),
  studentsTableBody:$('studentsTableBody'), studentsCountLabel:$('studentsCountLabel'), studentSearch:$('studentSearch'), refreshBtn:$('refreshBtn'),
  studentEditor:$('studentEditor'), editorStudentId:$('editorStudentId'), editFirstName:$('editFirstName'), editLastName:$('editLastName'), editStudentNumber:$('editStudentNumber'), editEntryYear:$('editEntryYear'), adminCourseList:$('adminCourseList'), newPin:$('newPin'), saveStudentBtn:$('saveStudentBtn'), cancelEditBtn:$('cancelEditBtn'), editorMessage:$('editorMessage'),
  catalogFile:$('catalogFile'), catalogPreview:$('catalogPreview'), applyCatalogBtn:$('applyCatalogBtn'), catalogMessage:$('catalogMessage'), currentCatalogId:$('currentCatalogId'), currentCatalogTime:$('currentCatalogTime'), catalogEntriesBody:$('catalogEntriesBody'), catalogCoursesBody:$('catalogCoursesBody'),
  demandTableBody:$('demandTableBody'), overlapTableBody:$('overlapTableBody'),
  downloadSchedulerBtn:$('downloadSchedulerBtn'), exportMessage:$('exportMessage'), exportStudents:$('exportStudents'), exportSelections:$('exportSelections'), exportOverlaps:$('exportOverlaps'), exportCatalogId:$('exportCatalogId'),
  clearAllStudentsBtn:$('clearAllStudentsBtn'), systemMessage:$('systemMessage')
};

let state={students:[],demand:[],overlap:[],courses:[],entries:[],settings:{},editingId:null,pendingCatalog:null};
function msg(el,text='',kind=''){if(!el)return;el.textContent=text;el.className='message'+(text?' show':'')+(kind?' '+kind:'');}
function fmtDate(v){if(!v)return '—';try{return new Date(v).toLocaleString('fa-IR');}catch{return v;}}
function faLevel(level){return level==='Graduate'?'کارشناسی ارشد':level==='PhD'?'دکتری':'کارشناسی';}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function entryLabel(id){const e=state.entries.find(x=>String(x.id)===String(id));return e?(e.label_fa||e.id):id;}
function selectedAdminCourses(){return [...document.querySelectorAll('.admin-course-check:checked')].map(x=>x.value);}
function pairKey(a,b){return [String(a),String(b)].sort().join('|||');}
function downloadJson(filename,payload){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}

function buildDetailedOverlaps(){
  const courseById=new Map(state.courses.map(c=>[String(c.id),c]));const pairs=new Map();
  for(const student of state.students){const ids=[...new Set((student.course_ids||[]).map(String))].sort();for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const a=ids[i],b=ids[j],key=pairKey(a,b);if(!pairs.has(key))pairs.set(key,{course_1_id:a,course_2_id:b,students:[]});pairs.get(key).students.push({student_number:String(student.student_number||''),first_name:String(student.first_name||''),last_name:String(student.last_name||''),entry_year:String(student.entry_year||'')});}}
  return [...pairs.values()].map(r=>{const c1=courseById.get(r.course_1_id)||{},c2=courseById.get(r.course_2_id)||{};return {...r,course_1:c1.name_fa||r.course_1_id,course_2:c2.name_fa||r.course_2_id,common_students:r.students.length};}).sort((a,b)=>b.common_students-a.common_students||String(a.course_1).localeCompare(String(b.course_1),'fa'));
}
function buildSchedulerExport(){
  const generatedAt=new Date().toISOString(),overlaps=buildDetailedOverlaps();
  const students=state.students.map(s=>({student_number:String(s.student_number||''),first_name:String(s.first_name||''),last_name:String(s.last_name||''),entry_year:String(s.entry_year||''),course_ids:(s.course_ids||[]).map(String),course_names:(s.course_names||[]).map(String),updated_at:s.updated_at||null}));
  const entries=state.entries.map(e=>({id:String(e.id||''),label_fa:String(e.label_fa||e.id||''),level:String(e.level||''),active:e.active!==false,sort_order:Number(e.sort_order||0)}));
  const courses=state.courses.map(c=>({id:String(c.id||''),name_fa:String(c.name_fa||''),instructor:String(c.instructor||''),credits:Number(c.credits||0),level:String(c.level||''),main_entry:String(c.main_entry||''),allowed_entries:(c.allowed_entries||[]).map(String),out_of_chart:!!c.out_of_chart,active:c.active!==false}));
  return {schema_version:'lu-stat-prereg-scheduler-v1',catalog_contract:'scheduler-stable-ids-v1',catalog_id:String(state.settings.catalog_id||''),catalog_exported_at:String(state.settings.catalog_exported_at||''),generated_at:generatedAt,source:'LU Statistics Preregistration v1.5',summary:{student_count:students.length,selection_count:students.reduce((n,s)=>n+s.course_ids.length,0),course_count:courses.length,active_course_count:courses.filter(c=>c.active).length,entry_count:entries.length,active_entry_count:entries.filter(e=>e.active).length,overlap_pair_count:overlaps.length},entries,courses,students,overlaps};
}
function exportSchedulerFile(){if(!state.settings.catalog_id)return msg(els.exportMessage,'ابتدا کاتالوگ University Scheduler را در بخش «کاتالوگ آموزشی» وارد کن.','error');const payload=buildSchedulerExport();const stamp=new Date().toISOString().replace(/[:.]/g,'-');downloadJson(`preregistration_scheduler_${stamp}.json`,payload);msg(els.exportMessage,`فایل مخصوص برنامه‌ریز با ${payload.summary.student_count.toLocaleString('fa-IR')} دانشجو ساخته شد. شناسه کاتالوگ: ${payload.catalog_id}`,'ok');}

async function signIn(){if(!client)return msg(els.loginMessage,'اتصال Supabase در config.js تنظیم نشده است.','error');const email=els.adminEmail.value.trim(),password=els.adminPassword.value;if(!email||!password)return msg(els.loginMessage,'ایمیل و رمز عبور را وارد کنید.','error');els.loginBtn.disabled=true;msg(els.loginMessage,'در حال ورود…');const {data,error}=await client.auth.signInWithPassword({email,password});els.loginBtn.disabled=false;if(error)return msg(els.loginMessage,'ورود ناموفق بود: '+error.message,'error');await showAdmin(data.user);}
async function signOut(){await client.auth.signOut();location.reload();}
async function showAdmin(user){els.loginCard.classList.add('hidden');els.adminApp.classList.remove('hidden');els.logoutBtn.classList.remove('hidden');els.adminUser.textContent=user?.email||'';await loadDashboard();}
async function loadDashboard(){
  const {data,error}=await client.rpc('admin_dashboard');
  if(error){els.adminApp.classList.add('hidden');els.loginCard.classList.remove('hidden');els.logoutBtn.classList.add('hidden');return msg(els.loginMessage,'این حساب وارد شده است اما دسترسی مدیر برای آن تعریف نشده است. ابتدا add_admin.sql را در Supabase اجرا کنید.','error');}
  state.settings=data?.settings||{};state.entries=data?.entries||[];state.courses=data?.courses||[];state.students=data?.students||[];state.demand=data?.course_demand||[];state.overlap=data?.course_overlap||[];
  const selections=state.students.reduce((a,s)=>a+(s.course_ids||[]).length,0);
  els.statStudents.textContent=state.students.length.toLocaleString('fa-IR');els.statSelections.textContent=selections.toLocaleString('fa-IR');els.statCourses.textContent=state.courses.filter(c=>c.active!==false).length.toLocaleString('fa-IR');els.statEntries.textContent=state.entries.filter(e=>e.active!==false).length.toLocaleString('fa-IR');els.statOverlaps.textContent=buildDetailedOverlaps().length.toLocaleString('fa-IR');
  renderStatus();renderStudents();renderCatalog();renderDemand();renderOverlap();refreshExportSummary();
}
function renderStatus(){const open=!!state.settings.registration_open;els.registrationStatusBadge.textContent=open?'فعال':'غیرفعال';els.registrationStatusBadge.className='status-badge '+(open?'active':'inactive');els.toggleRegistrationBtn.textContent=open?'غیرفعال کردن پیش‌ثبت‌نام':'فعال کردن پیش‌ثبت‌نام';els.toggleRegistrationBtn.className=open?'secondary':'primary';els.closedMessageInput.value=state.settings.closed_message||'پیش ثبت نام تا شروع ترم آینده توسط ادمین غیر فعال شده است و امکان ثبت یا ویرایش وجود ندارد.';els.catalogStatusText.textContent=state.settings.catalog_id?`کاتالوگ ${state.settings.catalog_id} · ورود ${fmtDate(state.settings.catalog_imported_at)}`:'کاتالوگ هنوز وارد نشده است.';}
async function saveStatus(openOverride=null){const next=openOverride===null?!!state.settings.registration_open:!!openOverride;const {data,error}=await client.rpc('admin_set_registration_status',{p_open:next,p_message:els.closedMessageInput.value.trim()});if(error||!data?.ok)return msg(els.statusMessage,data?.message||error?.message||'ثبت وضعیت انجام نشد.','error');msg(els.statusMessage,next?'سامانه پیش‌ثبت‌نام فعال شد.':'سامانه پیش‌ثبت‌نام غیرفعال شد.','ok');await loadDashboard();}
async function toggleStatus(){await saveStatus(!state.settings.registration_open);}

function renderStudents(){const q=els.studentSearch.value.trim().toLowerCase();const rows=state.students.filter(s=>`${s.first_name} ${s.last_name} ${s.student_number} ${s.entry_year} ${(s.course_names||[]).join(' ')}`.toLowerCase().includes(q));els.studentsCountLabel.textContent=`${rows.length.toLocaleString('fa-IR')} نفر`;els.studentsTableBody.innerHTML=rows.map(s=>`<tr><td><strong>${esc(s.first_name)} ${esc(s.last_name)}</strong></td><td>${esc(s.student_number)}</td><td>${esc(entryLabel(s.entry_year))}<div class="muted tiny-id">${esc(s.entry_year)}</div></td><td><div class="student-courses"><strong>${(s.course_ids||[]).length.toLocaleString('fa-IR')} درس:</strong> ${esc((s.course_names||[]).join('، '))}</div></td><td>${fmtDate(s.updated_at)}</td><td><button class="mini-btn" data-edit-student="${s.id}">ویرایش</button> <button class="mini-btn danger" data-delete-student="${s.id}">حذف</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">دانشجویی ثبت نشده است.</td></tr>';document.querySelectorAll('[data-edit-student]').forEach(b=>b.addEventListener('click',()=>openStudentEditor(b.dataset.editStudent)));document.querySelectorAll('[data-delete-student]').forEach(b=>b.addEventListener('click',()=>deleteStudent(b.dataset.deleteStudent)));}
function renderStudentEntrySelect(selected){els.editEntryYear.innerHTML=state.entries.map(e=>`<option value="${e.id}">${esc(e.label_fa||e.id)}</option>`).join('');els.editEntryYear.value=selected||'';}
function openStudentEditor(id){const s=state.students.find(x=>x.id===id);if(!s)return;state.editingId=id;els.editFirstName.value=s.first_name;els.editLastName.value=s.last_name;els.editStudentNumber.value=s.student_number;renderStudentEntrySelect(s.entry_year);els.newPin.value='';els.editorStudentId.textContent=`شماره دانشجویی فعلی: ${s.student_number}`;const wanted=new Set(s.course_ids||[]);els.adminCourseList.innerHTML=state.courses.map(c=>`<label class="admin-course-item"><input class="admin-course-check" type="checkbox" value="${c.id}" ${wanted.has(c.id)?'checked':''}><span>${esc(c.name_fa)} <span class="muted">· ${esc(c.instructor)}</span></span></label>`).join('');msg(els.editorMessage);els.studentEditor.classList.remove('hidden');els.studentEditor.scrollIntoView({behavior:'smooth',block:'start'});}
function closeStudentEditor(){state.editingId=null;els.studentEditor.classList.add('hidden');msg(els.editorMessage);}
async function saveStudent(){const ids=selectedAdminCourses();if(!ids.length)return msg(els.editorMessage,'حداقل یک درس باید انتخاب شده باشد.','error');const pin=els.newPin.value.trim();if(pin&&!/^\d{4,8}$/.test(pin))return msg(els.editorMessage,'کد ویرایش جدید باید ۴ تا ۸ رقم باشد.','error');els.saveStudentBtn.disabled=true;msg(els.editorMessage,'در حال ثبت…');const {data,error}=await client.rpc('admin_update_registration',{p_registration_id:state.editingId,p_student_number:els.editStudentNumber.value.trim(),p_first_name:els.editFirstName.value.trim(),p_last_name:els.editLastName.value.trim(),p_entry_year:els.editEntryYear.value,p_course_ids:ids,p_new_edit_pin:pin||null});els.saveStudentBtn.disabled=false;if(error||!data?.ok)return msg(els.editorMessage,data?.message||error?.message||'ویرایش انجام نشد.','error');msg(els.editorMessage,'تغییرات با موفقیت ثبت شد.','ok');await loadDashboard();setTimeout(closeStudentEditor,600);}
async function deleteStudent(id){const s=state.students.find(x=>x.id===id);if(!s)return;if(!confirm(`اطلاعات ${s.first_name} ${s.last_name} با شماره دانشجویی ${s.student_number} به‌طور کامل حذف شود؟`))return;const {data,error}=await client.rpc('admin_delete_registration',{p_registration_id:id});if(error||!data?.ok)return alert(data?.message||error?.message||'حذف انجام نشد.');if(state.editingId===id)closeStudentEditor();await loadDashboard();}

function renderCatalog(){els.currentCatalogId.textContent=state.settings.catalog_id||'—';els.currentCatalogTime.textContent=state.settings.catalog_id?`خروجی Scheduler: ${fmtDate(state.settings.catalog_exported_at)} · ورود به سایت: ${fmtDate(state.settings.catalog_imported_at)}`:'هنوز کاتالوگی وارد نشده است.';els.catalogEntriesBody.innerHTML=state.entries.map(e=>`<tr><td><code>${esc(e.id)}</code></td><td>${esc(e.label_fa||e.id)}</td><td>${faLevel(e.level)}</td><td>${Number(e.sort_order||0).toLocaleString('fa-IR')}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">ورودی‌ای وجود ندارد.</td></tr>';els.catalogCoursesBody.innerHTML=state.courses.map(c=>`<tr><td><code>${esc(c.id)}</code></td><td><strong>${esc(c.name_fa)}</strong></td><td>${esc(c.instructor)}</td><td>${Number(c.credits||0).toLocaleString('fa-IR')}</td><td>${faLevel(c.level)}</td><td>${esc(entryLabel(c.main_entry))}</td><td>${esc((c.allowed_entries||[]).map(entryLabel).join('، '))}</td><td>${c.out_of_chart?'بله':'خیر'}</td></tr>`).join('')||'<tr><td colspan="8" class="muted">درسی وجود ندارد.</td></tr>';}
function validateCatalog(obj){return obj&&obj.schema_version==='lu-stat-prereg-catalog-v1'&&obj.catalog_contract==='scheduler-stable-ids-v1'&&obj.catalog_id&&Array.isArray(obj.entries)&&Array.isArray(obj.courses);}
async function readCatalogFile(){state.pendingCatalog=null;els.applyCatalogBtn.disabled=true;els.catalogPreview.classList.add('hidden');msg(els.catalogMessage);const f=els.catalogFile.files?.[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!validateCatalog(obj))throw new Error('فایل انتخاب‌شده کاتالوگ معتبر University Scheduler نیست.');state.pendingCatalog=obj;els.catalogPreview.innerHTML=`<strong>پیش‌نمایش کاتالوگ</strong><div class="catalog-preview-grid"><div class="catalog-preview-item"><span>شناسه کاتالوگ</span><b>${esc(obj.catalog_id)}</b></div><div class="catalog-preview-item"><span>زمان خروجی Scheduler</span><b>${esc(fmtDate(obj.generated_at))}</b></div><div class="catalog-preview-item"><span>تعداد درس</span><b>${Number(obj.courses.length).toLocaleString('fa-IR')}</b></div><div class="catalog-preview-item"><span>تعداد ورودی</span><b>${Number(obj.entries.length).toLocaleString('fa-IR')}</b></div></div>`;els.catalogPreview.classList.remove('hidden');els.applyCatalogBtn.disabled=false;}catch(e){msg(els.catalogMessage,e.message,'error');}}
async function applyCatalog(){if(!state.pendingCatalog)return;els.applyCatalogBtn.disabled=true;msg(els.catalogMessage,'در حال اعمال کاتالوگ…');const {data,error}=await client.rpc('admin_import_catalog',{p_catalog:state.pendingCatalog});els.applyCatalogBtn.disabled=false;if(error||!data?.ok)return msg(els.catalogMessage,data?.message||error?.message||'اعمال کاتالوگ انجام نشد.','error');msg(els.catalogMessage,`کاتالوگ با موفقیت وارد شد: ${Number(data.course_count).toLocaleString('fa-IR')} درس و ${Number(data.entry_count).toLocaleString('fa-IR')} ورودی. سامانه تا زمان فعال‌کردن توسط مدیر بسته می‌ماند.`,'ok');state.pendingCatalog=null;els.catalogFile.value='';els.catalogPreview.classList.add('hidden');await loadDashboard();}

function renderDemand(){els.demandTableBody.innerHTML=state.demand.filter(r=>r.active!==false).sort((a,b)=>Number(b.student_count||0)-Number(a.student_count||0)).map(r=>`<tr><td>${esc(r.name_fa)}</td><td>${esc(r.instructor)}</td><td>${faLevel(r.level)}</td><td><strong>${Number(r.student_count).toLocaleString('fa-IR')}</strong></td></tr>`).join('')||'<tr><td colspan="4" class="muted">درسی وجود ندارد.</td></tr>';}
function renderOverlap(){const detailed=buildDetailedOverlaps();els.overlapTableBody.innerHTML=detailed.map(r=>{const people=(r.students||[]).map(s=>`<li>${esc(s.first_name)} ${esc(s.last_name)} · ${esc(s.student_number)} · ${esc(entryLabel(s.entry_year))}</li>`).join('');return `<tr><td>${esc(r.course_1)}</td><td>${esc(r.course_2)}</td><td><strong>${Number(r.common_students).toLocaleString('fa-IR')}</strong></td><td class="overlap-students"><details><summary>مشاهده ${Number(r.common_students).toLocaleString('fa-IR')} نفر</summary><ul class="overlap-students-list">${people}</ul></details></td></tr>`;}).join('')||'<tr><td colspan="4" class="muted">هنوز جفت‌درسی با دانشجوی مشترک وجود ندارد.</td></tr>';}
function refreshExportSummary(){const overlaps=buildDetailedOverlaps(),selections=state.students.reduce((n,s)=>n+(s.course_ids||[]).length,0);els.exportStudents.textContent=state.students.length.toLocaleString('fa-IR');els.exportSelections.textContent=selections.toLocaleString('fa-IR');els.exportOverlaps.textContent=overlaps.length.toLocaleString('fa-IR');els.exportCatalogId.textContent=state.settings.catalog_id||'—';}
async function clearAllStudents(){const phrase='حذف همه اطلاعات';const typed=prompt(`تمام اطلاعات دانشجویان و انتخاب درس‌های آن‌ها حذف می‌شود. کاتالوگ و حساب مدیر باقی می‌ماند و سامانه غیرفعال می‌شود.\n\nبرای تأیید دقیقاً بنویس:\n${phrase}`,'');if(typed!==phrase)return msg(els.systemMessage,'عملیات لغو شد؛ عبارت تأیید صحیح وارد نشد.','error');els.clearAllStudentsBtn.disabled=true;msg(els.systemMessage,'در حال حذف اطلاعات دانشجویان…');const {data,error}=await client.rpc('admin_clear_all_registrations');els.clearAllStudentsBtn.disabled=false;if(error||!data?.ok)return msg(els.systemMessage,data?.message||error?.message||'پاک‌سازی انجام نشد.','error');msg(els.systemMessage,`${Number(data.deleted_students||0).toLocaleString('fa-IR')} دانشجو و ${Number(data.deleted_selections||0).toLocaleString('fa-IR')} انتخاب درس حذف شد. سامانه پیش‌ثبت‌نام نیز غیرفعال شد.`,'ok');await loadDashboard();}

function switchTab(tab){document.querySelectorAll('.admin-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const panels={students:$('tabStudents'),catalog:$('tabCatalog'),demand:$('tabDemand'),overlap:$('tabOverlap'),scheduler:$('tabScheduler'),system:$('tabSystem')};Object.entries(panels).forEach(([name,panel])=>panel?.classList.toggle('hidden',name!==tab));if(tab==='scheduler')refreshExportSummary();if(tab!=='students')closeStudentEditor();}
document.querySelectorAll('.admin-tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
els.loginBtn.addEventListener('click',signIn);els.logoutBtn.addEventListener('click',signOut);els.studentSearch.addEventListener('input',renderStudents);els.refreshBtn.addEventListener('click',loadDashboard);els.saveStudentBtn.addEventListener('click',saveStudent);els.cancelEditBtn.addEventListener('click',closeStudentEditor);
els.catalogFile.addEventListener('change',readCatalogFile);els.applyCatalogBtn.addEventListener('click',applyCatalog);els.downloadSchedulerBtn.addEventListener('click',exportSchedulerFile);els.clearAllStudentsBtn.addEventListener('click',clearAllStudents);els.toggleRegistrationBtn.addEventListener('click',toggleStatus);els.saveStatusBtn.addEventListener('click',()=>saveStatus(null));
(async()=>{if(!configured)return msg(els.loginMessage,'ابتدا config.js را با API URL و Publishable Key تنظیم کنید.','error');const {data:{session}}=await client.auth.getSession();if(session?.user)await showAdmin(session.user);})();
